# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/agarioisgud/aml

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/agarioisgud/aml

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/agarioisgud/aml/CMakeFiles /home/agarioisgud/aml//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/agarioisgud/aml/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named aml

# Build rule for target.
aml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aml
.PHONY : aml

# fast build rule for target.
aml/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/build
.PHONY : aml/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/main.cpp.s
.PHONY : main.cpp.s

src/inputReciver.o: src/inputReciver.cpp.o

.PHONY : src/inputReciver.o

# target to build an object file
src/inputReciver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/src/inputReciver.cpp.o
.PHONY : src/inputReciver.cpp.o

src/inputReciver.i: src/inputReciver.cpp.i

.PHONY : src/inputReciver.i

# target to preprocess a source file
src/inputReciver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/src/inputReciver.cpp.i
.PHONY : src/inputReciver.cpp.i

src/inputReciver.s: src/inputReciver.cpp.s

.PHONY : src/inputReciver.s

# target to generate assembly for a file
src/inputReciver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/src/inputReciver.cpp.s
.PHONY : src/inputReciver.cpp.s

src/lib.o: src/lib.cpp.o

.PHONY : src/lib.o

# target to build an object file
src/lib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/src/lib.cpp.o
.PHONY : src/lib.cpp.o

src/lib.i: src/lib.cpp.i

.PHONY : src/lib.i

# target to preprocess a source file
src/lib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/src/lib.cpp.i
.PHONY : src/lib.cpp.i

src/lib.s: src/lib.cpp.s

.PHONY : src/lib.s

# target to generate assembly for a file
src/lib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/src/lib.cpp.s
.PHONY : src/lib.cpp.s

src/shaderProgram.o: src/shaderProgram.cpp.o

.PHONY : src/shaderProgram.o

# target to build an object file
src/shaderProgram.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/src/shaderProgram.cpp.o
.PHONY : src/shaderProgram.cpp.o

src/shaderProgram.i: src/shaderProgram.cpp.i

.PHONY : src/shaderProgram.i

# target to preprocess a source file
src/shaderProgram.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/src/shaderProgram.cpp.i
.PHONY : src/shaderProgram.cpp.i

src/shaderProgram.s: src/shaderProgram.cpp.s

.PHONY : src/shaderProgram.s

# target to generate assembly for a file
src/shaderProgram.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/src/shaderProgram.cpp.s
.PHONY : src/shaderProgram.cpp.s

src/shaderResource.o: src/shaderResource.cpp.o

.PHONY : src/shaderResource.o

# target to build an object file
src/shaderResource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/src/shaderResource.cpp.o
.PHONY : src/shaderResource.cpp.o

src/shaderResource.i: src/shaderResource.cpp.i

.PHONY : src/shaderResource.i

# target to preprocess a source file
src/shaderResource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/src/shaderResource.cpp.i
.PHONY : src/shaderResource.cpp.i

src/shaderResource.s: src/shaderResource.cpp.s

.PHONY : src/shaderResource.s

# target to generate assembly for a file
src/shaderResource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/src/shaderResource.cpp.s
.PHONY : src/shaderResource.cpp.s

src/uniform.o: src/uniform.cpp.o

.PHONY : src/uniform.o

# target to build an object file
src/uniform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/src/uniform.cpp.o
.PHONY : src/uniform.cpp.o

src/uniform.i: src/uniform.cpp.i

.PHONY : src/uniform.i

# target to preprocess a source file
src/uniform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/src/uniform.cpp.i
.PHONY : src/uniform.cpp.i

src/uniform.s: src/uniform.cpp.s

.PHONY : src/uniform.s

# target to generate assembly for a file
src/uniform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/src/uniform.cpp.s
.PHONY : src/uniform.cpp.s

src/window.o: src/window.cpp.o

.PHONY : src/window.o

# target to build an object file
src/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/src/window.cpp.o
.PHONY : src/window.cpp.o

src/window.i: src/window.cpp.i

.PHONY : src/window.i

# target to preprocess a source file
src/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/src/window.cpp.i
.PHONY : src/window.cpp.i

src/window.s: src/window.cpp.s

.PHONY : src/window.s

# target to generate assembly for a file
src/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aml.dir/build.make CMakeFiles/aml.dir/src/window.cpp.s
.PHONY : src/window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... aml"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/inputReciver.o"
	@echo "... src/inputReciver.i"
	@echo "... src/inputReciver.s"
	@echo "... src/lib.o"
	@echo "... src/lib.i"
	@echo "... src/lib.s"
	@echo "... src/shaderProgram.o"
	@echo "... src/shaderProgram.i"
	@echo "... src/shaderProgram.s"
	@echo "... src/shaderResource.o"
	@echo "... src/shaderResource.i"
	@echo "... src/shaderResource.s"
	@echo "... src/uniform.o"
	@echo "... src/uniform.i"
	@echo "... src/uniform.s"
	@echo "... src/window.o"
	@echo "... src/window.i"
	@echo "... src/window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

